export const MENU_ICON_CATEGORIES = [
  'Todos',
  'General',
  'Personas',
  'Seguridad',
  'Administración',
  'Navegación',
  'Archivos',
  'Comunicación',
  'Calendario',
  'Configuración',
] as const;

export type MenuIconCategory = (typeof MENU_ICON_CATEGORIES)[number];

export interface MenuIconOption {
  readonly name: string;
  readonly category: Exclude<MenuIconCategory, 'Todos'>;
}

export const MENU_ICON_CATALOG: readonly MenuIconOption[] = [
  { name: 'menu', category: 'General' },
  { name: 'apps', category: 'General' },
  { name: 'dashboard', category: 'General' },
  { name: 'home', category: 'Navegación' },
  { name: 'search', category: 'General' },
  { name: 'settings', category: 'Configuración' },
  { name: 'tune', category: 'Configuración' },
  { name: 'build', category: 'Configuración' },
  { name: 'manage_accounts', category: 'Administración' },
  { name: 'admin_panel_settings', category: 'Seguridad' },
  { name: 'shield', category: 'Seguridad' },
  { name: 'lock', category: 'Seguridad' },
  { name: 'lock_open', category: 'Seguridad' },
  { name: 'key', category: 'Seguridad' },
  { name: 'verified_user', category: 'Seguridad' },
  { name: 'policy', category: 'Seguridad' },
  { name: 'person', category: 'Personas' },
  { name: 'person_add', category: 'Personas' },
  { name: 'group', category: 'Personas' },
  { name: 'groups', category: 'Personas' },
  { name: 'badge', category: 'Personas' },
  { name: 'business', category: 'Administración' },
  { name: 'domain', category: 'Administración' },
  { name: 'account_balance', category: 'Administración' },
  { name: 'list_alt', category: 'Administración' },
  { name: 'check_circle', category: 'General' },
  { name: 'info', category: 'General' },
  { name: 'help', category: 'General' },
  { name: 'notifications', category: 'Comunicación' },
  { name: 'mail', category: 'Comunicación' },
  { name: 'chat', category: 'Comunicación' },
  { name: 'forum', category: 'Comunicación' },
  { name: 'send', category: 'Comunicación' },
  { name: 'calendar_month', category: 'Calendario' },
  { name: 'event', category: 'Calendario' },
  { name: 'today', category: 'Calendario' },
  { name: 'schedule', category: 'Calendario' },
  { name: 'folder', category: 'Archivos' },
  { name: 'folder_open', category: 'Archivos' },
  { name: 'description', category: 'Archivos' },
  { name: 'article', category: 'Archivos' },
  { name: 'upload_file', category: 'Archivos' },
  { name: 'download', category: 'Archivos' },
  { name: 'print', category: 'Archivos' },
  { name: 'arrow_back', category: 'Navegación' },
  { name: 'arrow_forward', category: 'Navegación' },
  { name: 'chevron_left', category: 'Navegación' },
  { name: 'chevron_right', category: 'Navegación' },
  { name: 'expand_more', category: 'Navegación' },
  { name: 'expand_less', category: 'Navegación' },
  { name: 'open_in_new', category: 'Navegación' },
  { name: 'view_list', category: 'General' },
  { name: 'view_module', category: 'General' },
  { name: 'table_chart', category: 'General' },
  { name: 'analytics', category: 'Administración' },
  { name: 'bar_chart', category: 'Administración' },
  { name: 'history', category: 'Administración' },
  { name: 'edit', category: 'Administración' },
  { name: 'delete_outline', category: 'Administración' },
  { name: 'restore', category: 'Administración' },
] as const;
